name: Publish Package

on:
  release:
    types: [published]  # Se dispara cuando creas un Release en GitHub

jobs:
  pypi-publish:
    name: Build, TestPyPI and PyPI Publish
    runs-on: ubuntu-latest
    
    # ⚠️ OBLIGATORIO para que OpenID Connect (Trusted Publishing) funcione
    permissions:
      id-token: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"  # 👈 Coincide exactamente con el requires-python >=3.14 de tu pyproject.toml
          
      - name: Install Poetry
        uses: snok/install-poetry@v1
        
      - name: Build package with Poetry
        run: poetry build
        
      # 1️⃣ Primero lo subimos a TestPyPI para pruebas
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          
      # 2️⃣ Después lo subimos al PyPI oficial de producción
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1